services:
  # ======================================================================================
  #                                Serviços de Infraestrutura
  # ======================================================================================
  postgres_db:
    image: postgres:13-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d main_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  emqx:
    image: emqx/emqx:5.8
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - "EMQX_NAME=emqx-node1"
      - "EMQX_HOST=emqx"
      - "EMQX_ALLOW_ANONYMOUS=true"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_etc:/opt/emqx/etc
      - emqx_log:/opt/emqx/log
    networks:
      - app-network

  # ======================================================================================
  #                                Serviços de API (Interface)
  # ======================================================================================
  servico-autenticacao:
    build: ./servico-autenticacao
    container_name: servico-autenticacao
    command: python manage.py runserver 0.0.0.0:8001
    env_file: .env
    volumes:
      - ./servico-autenticacao:/app
    ports:
      - "8001:8001"
    networks:
      - app-network

  middleware:
    build: ./middleware
    container_name: middleware
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - DB_SERVICE_URL=http://servico-banco-dados:8002/
    volumes:
      - ./middleware:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      servico-permissao:
        condition: service_started
    networks:
      - app-network

  # ======================================================================================
  #                               Serviços de Lógica (Workers)
  # ======================================================================================
  servico-banco-dados:
    build: ./servico-banco-dados
    container_name: servico-banco-dados
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    env_file: .env
    volumes:
      - ./servico-banco-dados:/app
    ports:
      - "8002:8002"
    environment:
      - DB_NAME=main_db
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_HOST=postgres_db
      - DB_PORT=5432
    restart: on-failure
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 8002))\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s

  servico-permissao:
    build: ./servico-permissao
    container_name: servico-permissao
    command: celery -A tasks worker --loglevel=info -Q permission_queue
    env_file: .env
    volumes:
      - ./servico-permissao:/app
    restart: on-failure
    depends_on:
      servico-banco-dados:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  servico-log:
    build: ./servico-log
    container_name: servico-log
    command: celery -A tasks worker --loglevel=info -Q log_queue
    env_file: .env
    volumes:
      - ./servico-log:/app
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      servico-banco-dados:
        condition: service_healthy
    networks:
      - app-network

  servico-porta:
    build: ./servico-porta
    container_name: servico-porta
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MQTT_BROKER_HOST=emqx
      - DB_SERVICE_URL=http://servico-banco-dados:8002/api
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      emqx:
        condition: service_started
      servico-banco-dados:
        condition: service_healthy

# ======================================================================================
#                                   Redes e Volumes
# ======================================================================================
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  emqx_data:
  emqx_etc:
  emqx_log:
  rabbitmq_data: