# servico-porta/dockerfile
FROM python:3.11-slim

RUN apt-get update && apt-get install -y tzdata
ENV TZ=America/Sao_Paulo

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "bridge_service.py"]