# Generated by Django 5.1.5 on 2025-09-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coordinator",
            new_name="Aluno",
        ),
        migrations.RenameModel(
            old_name="Common",
            new_name="PrestadorServico",
        ),
        migrations.AlterField(
            model_name="actoruser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Aluno", "Aluno"),
                    ("Servidor", "Servidor"),
                    ("PRESTADOR_SERVICO", "Prestador Servico"),
                ],
                default="Aluno",
                max_length=20,
            ),
        ),
    ]
