# Generated by Django 5.1.5 on 2025-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_coordinator_aluno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actoruser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Aluno", "Aluno"),
                    ("Servidor", "Servidor"),
                    ("Prestador Servico", "Prestador Servico"),
                ],
                default="Aluno",
                max_length=20,
            ),
        ),
    ]
