# Generated by Django 5.1.5 on 2025-09-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_coordinator_aluno_and_more"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermissionRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resources.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.actoruser",
                    ),
                ),
            ],
        ),
    ]
