# Generated by Django 5.1.5 on 2025-09-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_actoruser_role"),
        ("resources", "0002_userpermissionroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServidorViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="log_sala",
                        to="resources.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "Servidor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_servidor",
                        to="profiles.actoruser",
                    ),
                ),
            ],
        ),
    ]
