# Generated by Django 5.1.5 on 2025-09-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_actoruser_role"),
        ("resources", "0003_servidorviewlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidorviewlog",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "Servidor"},
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.actoruser",
            ),
        ),
    ]
