# Generated by Django 5.1.5 on 2025-09-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_actoruser_role"),
        ("resources", "0004_alter_servidorviewlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="iot",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="iots",
                to="resources.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="resources.department",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servidorviewlog",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="log_permissions",
                to="resources.room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userpermissionroom",
            unique_together={("user", "room")},
        ),
    ]
